---
abstract: 'KiokuDB Dancer session backend'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  Dancer: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.101610'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Session-KiokuDB
requires:
  Carp: 0
  Dancer::Config: 0
  Dancer::FileUtils: 0
  Dancer::Logger: 0
  Dancer::ModuleLoader: 0
  Dancer::Session::Abstract: 0
  KiokuDB: 0
resources:
  repository: http://github.com/xsawyerx/dancer-session-kiokudb
version: 0.01
